- hosts: all
  roles:
    - alacritty
    - awscli
    - bazel
    - borgbackup
    - chezmoi
    - deno
    - golang
    - gopass
    - helm
    - kubectl
    - neovim
    - ruby
    - smplayer
    - terraform
    - yarn
    - youtube-dl
