- hosts: all
  roles:
    - alacritty
    - awscli
    - borgbackup
    - chezmoi
    - golang
    - gopass
    - kubectl
    - neovim
    - nvidia
    - ruby
    - smplayer
    - yarn
    - youtube-dl
