- become: "yes"
  get_url:
    dest: /usr/local/bin/bazel
    mode: "0755"
    url: >-
      https://github.com/bazelbuild/bazel/releases/download/3.5.0/bazel-3.5.0-linux-x86_64
  name: Install bazel
