- become: "yes"
  name: Install gopass
  unarchive:
    creates: /usr/local/bin/gopass
    dest: /usr/local/bin
    extra_opts:
      - gopass
    remote_src: "yes"
    src: >-
      https://github.com/gopasspw/gopass/releases/download/v1.10.1/gopass-1.10.1-linux-amd64.tar.gz
