- become: "yes"
  dnf:
    name: >-
      https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm,
      https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-32.noarch.rpm
    state: present
  name: Install rpmfusion
- become: "yes"
  dnf:
    name: akmod-nvidia
    state: present
  name: Install nvidia
- get_url:
    dest: >-
      {{ ansible_env.HOME
      }}/Downloads/cuda-repo-fedora29-10-2-local-10.2.89-440.33.01-1.0-1.x86_64.rpm
    url: >-
      http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda-repo-fedora29-10-2-local-10.2.89-440.33.01-1.0-1.x86_64.rpm
  name: Download cuda
- become: "yes"
  dnf:
    name: >-
      xorg-x11-drv-nvidia-cuda, xorg-x11-drv-nvidia-cuda-libs, {{
      ansible_env.HOME
      }}/Downloads/cuda-repo-fedora29-10-2-local-10.2.89-440.33.01-1.0-1.x86_64.rpm
    state: present
  name: Install cuda
- become: "yes"
  lineinfile:
    line: >-
      exclude=akmod-nvidia*,kmod-nvidia*,*nvidia*,nvidia-*,cuda-nvidia-kmod-common,dkms-nvidia,nvidia-libXNVCtrl
    path: /etc/yum.repos.d/cuda-10-2-local-10.2.89-440.33.01.repo
  name: Exclude nvidia
- become: "yes"
  dnf:
    name: "ffmpeg, mpv, qt5, smplayer"
    state: present
  name: Install smplayer
