- args:
    creates: "{{ ansible_env.HOME }}/.nvm"
  name: Install node
  shell: >-
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh |
    bash && source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node
- args:
    creates: "{{ ansible_env.HOME }}/.yarn"
  name: Install yarn
  shell: "curl -o- -L https://yarnpkg.com/install.sh | bash"
