- become: "yes"
  name: Install docker
  unarchive:
    creates: /usr/local/bin/docker
    dest: /usr/local/bin
    extra_opts:
      - "--strip-components=1"
    remote_src: "yes"
    src: "https://download.docker.com/linux/static/stable/x86_64/docker-19.03.9.tgz"
